apps/crud/models.py
from apps.app import db

class User(db.Model):
    __tablename__ = "webtoons"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, index=True)
    author = db.Column(db.String, index=True)
    genre = db.Column(db.String, index=True)
    link = db.Column(db.String, index=True)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length

class Userform(FlaskForm):

    title = StringField(
        "♠",
        validators=[DataRequired(message="제목을 적어주세요"),Length(max=30, message="30자 이내로 작성바랍니다.")],
    )
    author = StringField(
        "◆",
        validators=[DataRequired(message="작가명을 적어주세요")],
    )
    genre = StringField(
        "♥",
        validators=[DataRequired(message="장르를 적어주세요")],
    )
    link = StringField(
        "♣",
        validators=[DataRequired(message="링크주소를 적어주세요")],
    )

    submit = SubmitField("UpDate!")
    

apps/crud/views.py
from flask import Blueprint, render_template, redirect, url_for
from apps.app import db
from apps.crud.models import User
from apps.crud.forms import Userform


crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static",
)

@crud.route("/")
def index():
    return render_template("crud/index.html")

@crud.route("/sql")
def sql():
    db.session.query(User).all()
    return "콘솔 로그를 확인해주세요"

@crud.route("/users/new", methods=["GET", "POST"])
def create_user():
    form = Userform()

    if form.validate_on_submit():
        user = User(
            title = form.title.data,
            author = form.author.data,
            genre = form.genre.data,
            link = form.link.data,
        )
        db.session.add(user)
        db.session.commit()

        return redirect(url_for("crud.users"))
    
    return render_template("crud/create.html", form=form)

@crud.route("/users")
def users():

    users = User.query.all()
    return render_template("crud/index.html", users=users)

@crud.route("/users/<user_id>", methods=["GET", "POST"])
def edit_user(user_id):
    form = Userform()

    user = User.query.filter_by(id=user_id).first()

    if form.validate_on_submit():
        # user.id = form.id.data
        user.title = form.title.data
        user.author = form.autor.data
        user.genre = form.genre.data
        user.link = form.link.data

        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    
    return render_template("crud/edit.html", user=user, form=form)

@crud.route("/users/<user_id>/delete", methods=["POST"])
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

apps/crud/templates/crud/create.html
<!DOCTYPE html>
<html class="create" lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>웹툰 목록에 추가</title>
    <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css')}}"
</head>
<body class="createbody">
    <div class="cdiv">
    <h1 class="listup">˝ Add My toon ˝</h1>
    
    <form class="listupform" style="display: inline-block;"
        action="{{ url_for('crud.create_user') }}"
        method="POST"
        novalidate="novalidate"
    >
    {{ form.csrf_token }}
    <p class="cp">
        {{ form.title.label }} {{ form.title(class="cpclass", placeholder="제목") }}
    </p>
    {% for error in form.title.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p class="cp">
        {{ form.author.label }} {{ form.author(class="cpclass",placeholder="작가") }}
    </p>
    {% for error in form.author.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p class="cp">
        {{ form.genre.label }} {{ form.genre(class="cpclass",placeholder="장르") }}
    </p>
    {% for error in form.genre.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p class="cp">
        {{ form.link.label }} {{ form.link(class="cpclass",placeholder="링크주소") }}
    </p>
    {% for error in form.link.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
     
    <p class="pp"><input class="addsubmit" type="submit" value="UpDate!"></p>
</form>
</div> 
</body>
</html>

apps/crud/templates/crud/edit.html
<!DOCTYPE html>
<html class="edit1" lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>목록 편집</title>
    <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css') }}"
</head>
<body class="editbody">
    <div class="div">
    <h1 class="edit">Edit  List</h1>

    <form class="editform" style="display: inline-block;"
        action="{{ url_for('crud.edit_user', user_id=user.id) }}"
        method="POST"
        novalidate="novalidate"
        >
        {{ form.csrf_token }}
        <p class="editp">
            {{ form.title.label }} {{ form.title(class="input",  placeholder="제목") }}
        </p>
        {% for error in form.title.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p class="editp">
            {{ form.author.label }} {{ form.author(class="input",placeholder="작가") }}
        </p>
        {% for error in form.author.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p class="editp">
            {{ form.genre.label }} {{ form.genre(class="input",placeholder="장르") }}
        </p>
        {% for error in form.genre.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p class="editp">
            {{ form.link.label }} {{ form.link(class="input",placeholder="링크주소") }}
        </p>
        {% for error in form.link.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p class="p1"><input class="in" type="submit" value="UpDate!"></p>
    </form>
    <form
        action="{{ url_for('crud.delete_user', user_id=user.id) }}" method="POST">
        {{ form.csrf_token }}
        <input class="in" type="submit" value="Delete!" >
    </form>
</div>
        
</body>
</html>

apps/crud/templates/crud/index.html
<!DOCTYPE html>
<html class="index" lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>웹툰 목록</title>
    <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css')}}"
</head>
<body class="toonlist">
    <h1 class="hh2">˝ MY WEBTOONS ˝</h1>
    <a class="newtoon" href="{{ url_for('crud.create_user') }}" style="display: inline-block;">☞ADD New WebToon☜</a>

    <table>
        <tr>
            <th>N   O</th>
            <th>T I T L E</th>
            <th>A U T H O R</th>
            <th>G E N R E</th>
            <th>L I N K</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>
                <a href="{{ url_for('crud.edit_user', user_id=user.id) }}">{{ user.id }}</a>
            </td>
            <td>{{ user.title }}</td>
            <td>{{ user.author }}</td>
            <td>{{ user.genre }}</td>
            <td>
                <a href="{{ user.link }}">click!!</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>